### ISSUE TITLE
🐛 [Bug]: ≈500ms Performance penalty using compression on and 'br' in 'Accept-Encoding'

### ISSUE THREAD

**Issue by the-hotmann** [gofiber/fiber#2722]
### Bug Description

Usually I by default set compression to `2` but today I noticed a problem when on fiber `v2.51.0`.

This is the config I use:

```
app.Use(
	compress.New(compress.Config{
		Level: 2,
	}),
)
```

I tested a bit and came to this conclusion:

1. direct call/access (about 5ms)
2. Nginx Proxy call (≈400-600ms)

a direct call will always be fast, but as soon as I access a fiber 2.51.0 pages I see TTFBs of at least 400-600ms.

This penalty just appears to be happening on the HTML part, not any static assets.
Turning off compression solves the problem entirely.

So I had multiple thoughts:

1. the user the docker container runs with does not have permission to write the compressed file and therefore takes long, but I discarted this thought, as this would also have to affect the direct call - which it does not.
2. I tought about have a wrong ProxyHeader and did some tests there, as there might be some different behaviour behind NPM (Nginx Proxy Manager) but also all of these tests did not lead to anything.

- This must be related to 2.51.0 as it just appears there.
- disableing compression fixes the problem entirely
- had a look at the changelog of 2.51.0, sounds like this changed some behaviour to upstreams/proxies: https://github.com/gofiber/fiber/pull/2678

### How to Reproduce

Actually already described above

### Expected Behavior

New features can have a performance penalty, but 400-600ms is not acceptable I guess?

### Fiber Version

v2.51.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
There is actually nothing in the last version that can trigger this
Can you go through the last versions in your setup

**Comment by ReneWerner87** [comment]
Ok thx

**Comment by nickajacks1** [comment]
To diagnose where the issue is you can add `app.Use(logger.New(logger.ConfigDefault))` to see how long fiber is taking.

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New()
	app.Use("/", logger.New(logger.ConfigDefault))
	app.Use("/", compress.New(compress.Config{Level: 2}))
	app.Static("/", "")
	app.Listen(":3030")
}
```
You will see logs that show approximately how long fiber took to process the request.
```
17:49:42 | 200 |    3.869307ms |       127.0.0.1 | GET     | /big.html       
17:49:45 | 200 |       75.42µs |       127.0.0.1 | GET     | /big.html       
17:49:47 | 200 |      53.825µs |       127.0.0.1 | GET     | /big.html       
17:49:47 | 200 |      42.185µs |       127.0.0.1 | GET     | /big.html       
```
So if it's significantly different between versions of fiber, there's a problem

**Comment by the-hotmann** [comment]
I always use the middleware logger. But this in this log it was not showing it - I can state that directly. Ofc there could be a discrepancy when using Nginx and Fiber, but I will test first and then provide all the info.

**Comment by the-hotmann** [comment]
Ok, I just performed some tests:

- `https://fibercompression-v2-49-0.hotmann.de`
- `https://fibercompression-v2-49-1.hotmann.de`
- `https://fibercompression-v2-49-2.hotmann.de`
- `https://fibercompression-v2-50-0.hotmann.de`
- `https://fibercompression-v2-51-0.hotmann.de`

and could not reproduce the bug. But I just noticed that  also added a custom function to the engine, to be able to render HTML as `unsafe` / `unescape` - maybe this was causing the problem in combination with `compression`


Here the added custom-function, which I added to the engine:

```
engine := html.New("../templates", ".html")
engine.AddFunc(
	"unescape", func(s string) template.HTML {
		return template.HTML(s)
	},
)
```

I will try some more tests and update the docker-images afterwards - so the links then will reflect the updated state

**Comment by ReneWerner87** [comment]
@the-hotmann so it cannot be reproduced? can we then close this issue until it is reproducible and then reopen it if necessary?

**Comment by the-hotmann** [comment]
I woul like to keep it open for some more hours, as I will re-try to reproduce it.
I will come back with feedback and if not be able to reproduce it, I will close it.

Thanks

**Comment by ReneWerner87** [comment]
ok

**Comment by nickajacks1** [comment]
Actually, I found a similar behavior on the above snippet I shared, but it still occurred as far back as v2.40.0.
When I get the html page through a browser, there is a several hundred millisecond delay before the first byte:
<img width="296" alt="chrome_4uqFbwpJeb" src="https://github.com/gofiber/fiber/assets/128185314/bc300b00-299e-4ee4-a308-017f538f2047">
If I refresh right away, there is no delay, but if I wait a few seconds and refresh, the delay occurs again.
The delay does not occur if I use curl. 
Using Express, the delay occurs on the first connection, but never again.
The connection is happening from windows to WSL (fiber) in my case.
I don't know enough about what a browser does on an HTTP get to know if this is the same thing you were experiencing or not, but indeed the same Initial Connection is very short when I connect to your example links.
<img width="280" alt="image" src="https://github.com/gofiber/fiber/assets/128185314/0e428d70-1828-42ee-a455-2532cc17cbfc">

**Comment by the-hotmann** [comment]
I did some more tests and could reproduce the error again.

Feel free to download all 5 versions/tags from this docker-image: https://hub.docker.com/r/h0tmann/go_fiber_test
and use this docker-compose:

```
version: '3'
services:

##########################
####### FIBER TEST #######
##########################

  go_fiber_2490:
    container_name: go_fiber_2490
    image: h0tmann/go_fiber_test:v2.49.0
    hostname: go_fiber_2490
    ports:
      - 8003:8003
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped

  go_fiber_2491:
    container_name: go_fiber_2491
    image: h0tmann/go_fiber_test:v2.49.1
    hostname: go_fiber_2491
    ports:
      - 8004:8003
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped

  go_fiber_2492:
    container_name: go_fiber_2492
    image: h0tmann/go_fiber_test:v2.49.2
    hostname: go_fiber_2492
    ports:
      - 8005:8003
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped

  go_fiber_2500:
    container_name: go_fiber_2500
    image: h0tmann/go_fiber_test:v2.50.0
    hostname: go_fiber_2500
    ports:
      - 8006:8003
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped

  go_fiber_2510:
    container_name: go_fiber_2510
    image: h0tmann/go_fiber_test:v2.51.0
    hostname: go_fiber_2510
    ports:
      - 8007:8003
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
```

Now use Nginx/NPM to point a domain to each of the containers.

You will end up with two possible URLs to call the very same container:

1. `http://domain.tld`
2. `123.123.123.123:8003` (`8003`-`8007`)

DO NOT TEST BEHIND CLOUDFLARE! Cloudflare (my public tests are proxyied throu Cloudflare) is somehow making the problem not showing up.


My public Tests are hosted like this:

`Client` => `Cloudflare` => `Nginx` => `Docker-Container`

My internal Tests are tested like this:

`Client` => `Nginx` => `Docker-Container` (Here the Problem shows up!)

I am more then happy to provide you guys with the new URLs, apparently they point to IPs which I dont want to share publicly. So feel free to contact me privately or setup your own testcase according to the tutorial above.


Also I tested on the Versions:
- `v2.49.0`
- `v2.49.1`
- `v2.49.2`
- `v2.50.0`
- `v2.51.0`

It happens on ALL of them.
BUT: Fiber itself reports times like `141.991µs` but the TTFB is soemwhere around `0.5s`.
